#' One Million Random Digits
#' 
#' One million random digits generated by the RAND Corporation in 1955 in the book \emph{A Million Random Digits with 100,000 Normal Deviates}.
#' 
#' @source \url{https://www.rand.org/content/dam/rand/pubs/monograph_reports/MR1418/MR1418.digits.txt.zip}
#' 
#' @references RAND (1955) \emph{A Million Random Digits with 100,000 Normal Deviates}. \url{https://www.rand.org/pubs/monograph_reports/MR1418/index2.html}
"rand_digits"
